### ISSUE TITLE
Feature Request: Support Backblaze B2 Storage

### ISSUE THREAD

**Issue by roock** [lemonsaurus/blackbox#128]
Backblaze B2 is a cheap storage provider and perfectly suited for storing backups.
There is a python SDK for Backblaze B2: https://github.com/Backblaze/b2-sdk-python

**Comment by onerandomusername** [comment]
This is already supported. You can use the `endpoint` and `bucket` configuration and point them towards backblaze's S3 API. https://help.backblaze.com/hc/en-us/articles/360047425453-Getting-Started-with-the-S3-Compatible-API

**Comment by lemonsaurus** [comment]
yeah, using the S3 API is the intended solution for this problem. We don't want to implement storage providers for things that support any kind of universal storage connection standards like S3.

**Comment by onerandomusername** [comment]
To be fair, backblaze could be added in the readme as another mention.
