### ISSUE TITLE
Configuration: Allow configuration via environment variables

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#20]
Right now, we require a `config.yml` file to contain all the secrets in order to configure the application. This is not always convenient, especially in container orchestration environments where secrets are managed through some external secrets manager.

Let's allow environment variable interpolation in the `config.yml` file in order to make this more flexible.

```yml
databases:
  - mongodb://{{ MONGO_USERNAME }}:{{ MONGO_PASSWORD }}@host:port
  - {{ POSTGRES_CONNECTION_STRING }}
```

## Implementation
Let's use Jinja to parse the config file as a template, and inject the entire environment into the renderer.

Pseudocode:
```py
config = Path("config.yml").read_text
parsed_config = config.render_template(**os.environ)
```

**Comment by lemonsaurus** [comment]
alternative solution:

We could just allow environment variables in the `config.yml` file, and then the user can configure them however they want.

e.g.
```yml
databases:
  - mongodb://{{ env.MONGO_USERNAME }}:{{ env.MONGO_PASSWORD }}@host:port
  - {{ env.POSTGRES_CONNECTION_STRING }}
```

**Comment by Inveracity** [comment]
I can try taking a stab at this if no one as picked it up yet?
