### ISSUE TITLE
Configuration: Allow databases to specify storage and notifiers to use.

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#25]
## Rationale
So, a user might have two databases, but these should not be backed up onto the same storage providers, and one of them should be notified to Discord while the other should go to Slack. How can we accommodate this?

One solution would be a more complex config file, but I want us to try to avoid this because it introduces additional user experience complexity to _all users_, even though this feature will only appeal to a few users. This is a bad UX investment.

Instead, let's handle it with optional connstring parameters!

## Implementation

Allow all database connstrings to take two extra parameters, `storage_providers` and `notifiers`.

For example, `redis://host:port?storage_providers=s3,dropbox&notifiers=slack` would specify that the redis database should be backed up onto S3 and Dropbox, and then notified to Slack.

These are strictly optional. By default it will use all notifiers and all storage providers.

Multiple values can be provided, and are **comma-separated**.

## But what if `s3` is ambiguous?
In #15, we propose implementing support for multiple handlers of the same kind. If the user has two S3 storage providers, and wants to only select one of them, we will need some way of identifying which one it is.

- If we have multiple providers of type `s3`, use all of them if a database specifies `storage_providers=s3`.
- Allow a user to specify an ID for notifiers and providers to disambiguate. For example, `s3://my.bucket.com?id=main_bucket` will associate this ID with the bucket.
- The database can now use this ID to select its target, e.g. `storage_providers=dropbox,main_bucket`

**Comment by kosayoda** [comment]
This will require a restructure of the current workflow. My suggestion is this:

1. Parse implemented Database/Storage/Notifier handlers and get the valid prefixes for each handler.
2. Parse the configuration connstrings and determine if it is valid:
    1. If the handler in the configuration does not match any valid prefixes, raise an error, otherwise:
    2. Notifiers and Storages are parsed first; This creates the notifier/storage instances for each connstring defined in the config and keeps track of the id for each of them. The instance is also added to a general id `all` and a handler id (`discord`, `s3`)
    3. Parse the database connstrings. Raise an error if the storage/notifiers selected are undefined. Create a Workflow object for each database, containing the storage and notifier instances selected for each database.
3. Start backup by going through all each workflow:
    1. Backup the database.
    2. Sync the backup to each storage provider selected.
    3. Submit the report to each notifier selected (using a method like `notifier.add_report(report)`).
4. Notify reports for each notifier defined.

I'd appreciate a better way too so let me know what you think.

**Comment by lemonsaurus** [comment]
Okay, so you basically want to go over all the handlers first to verify that all cross-references are valid, and _then_ we do the procedure. fair enough, that seems solid to me, it'll prevent blackbox from running half a backup procedure and then failing.

I'm not sure I understand exactly why this is _necessary_ for this change, but I don't think it sounds like a bad change so I don't feel the need to suggest an alternative implementation.

As we continue to add complexity to the main loop, we should ask ourselves if this complexity may be better contained in a sort of main application class. Feel free to refactor in that direction if it feels more convenient.
