### ISSUE TITLE
Configuration: Notifier frequency

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#28]
Currently, the notifiers will trigger for every time blackbox is run. This is not necessarily convenient:
- If someone wants backups every 10 minutes, it'll get _really_ spammy. In this case, we only really care about the notifiers if they fail.
- Kubernetes CronJobs are not guaranteed to run only once, so we may get double notifiers. The actual storage provider upload is idempotent (because it'll just overwrite the file if you run it twice the same day), but notifiers are not.

So, it would be convenient to be able to configure this to be a bit less noisy.

## Implementation
Let's implement a new config option, `notifier_frequency`, that tells us how often we should show success notifications. If `notifier_frequency` is set to 1 day, we only show a success notification once per day. **Failure notifications should always be shown.** 

I'm intentionally not specifying what format the frequency duration should be specified in. A fun solution would be something that supported a timestring like `1d12H` or something similar to that. We have examples of how to do this in https://github.com/python-discord/bot/blob/master/bot/utils/time.py. However, honestly, I'd be fine if this was just in minutes or something, and we could set it to `1440` for a day. Maybe that's simpler? Up to you.

**Comment by matacoder** [comment]
Suggestions:
1. Time interval for notification (10-18 for example)
2. Max frequency per day (0 unlimited, N), so we can divide (18-10)/N to get timedelta
3. Not agreed on `always send on fail`. If it would be message every 10 minutes, just let's make unified rule. 
4. We need to store database of sent times to calculate. Suggest simple json with last date and how many times sent already.

**Comment by lemonsaurus** [comment]
I think always sending on fail is a good default, because you normally want to know as soon as something is failing. I'd be open to making it possible to disable that behavior.

I don't really understand what the rationale is for intervals. To me it feels pointless to limit logs and webhooks to certain time intervals.

the purpose of this issue was to limit the noise generated by frequent successful backups, but I don't think of failures as noise. they are always relevant.

**Comment by matacoder** [comment]
But do you really need notification of success backup at 1 am?
Okay we will send at every failure without interval limitation but success?

**Comment by lemonsaurus** [comment]
It doesn't matter to me what time I get success notifications, I'm not gonna be checking my Slack at 1 AM. They'll be there when I check it the next day. It's just useful information to log. But I don't need to know that the backup succeeded 200 times yesterday. That's just noise. I want to know that it's running at least once per day, and I want to know if it fails. Everything else is noise to me.

**Comment by matacoder** [comment]
Fair point. May be we can add something like `By the way, it was successfully backed up 45 times since last notification`
