### ISSUE TITLE
CI: Publish to PyPI

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#32]
**NOTE: This issue is blocked by #31, but can be tackled once a solution for #31 has been merged.**

We'll want to set up a nice workflow to publish this application to PyPI whenever a new release is created. This is quite easy to do, look at https://github.com/python-discord/django-simple-bulma/blob/master/.github/workflows/release.yml for an example.

**Comment by Inveracity** [comment]
I'd say this is slightly higher priority as we need to claim the name now that it's available
