### ISSUE TITLE
Sanitize logging output

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#47]
We should not - under any circumstances - be allowing logging output to include the interpolated config values, since this can include passwords and other high-security secrets that we don't want to send over webhooks and emails or whatever.

This is pretty easy to solve, though. Just go through the logging output and replace all config values with asterisks or something.

**Comment by matacoder** [comment]
I volunteer to perform this beginner-level task

**Comment by matacoder** [comment]
@lemonsaurus should it be only class BlackboxDatabase(BlackboxHandler) self.output or we should mask logger errors/warnings too?

**Comment by lemonsaurus** [comment]
good question. Since we technically might implement any storage or database in the future or even use the notifiers in strange new ways, I think my preferred approach is to somehow make the notifiers sanitize their output (whatever you end up feeding them) before sending it.

Maybe we can solve this at an abstract level so that all present and future notifiers must implement sanitization?

The sanitization should just be to specifically look for the secrets that are specified in the config and sanitizing those. Only the values, not the keys.
