### ISSUE TITLE
Publish Docker images with version numbers

### ISSUE THREAD

**Issue by jb3** [lemonsaurus/blackbox#60]
Right now there is no way to fetch a specific semver from Docker Hub, as the only versions pushed are `:latest` and `:{sha}`.

Images should be pushed with the semvers as they are for PyPI:

<img width="834" alt="Screenshot 2021-03-26 at 14 49 54" src="https://user-images.githubusercontent.com/20439493/112649660-8a0c9c00-8e42-11eb-83b3-a059255fa73d.png">

It's not ideal to pin to SHAs and pinning to :latest isn't a great idea for production, so tags along the lines of `:2.0.0` or `:2-latest` (to fetch anything 2.X.X) would be nice.

**Comment by matacoder** [comment]
I've tested in my repo the following approach:
```
      # Create a version.month.day tag for the container repositories
      - name: Create Container Tag
        id: date
        run: |
          MONTH=`date +'%m'`
          DAY=`date +'%d'`
          tag=1.$MONTH.$DAY
          echo "::set-output name=tag::$tag"
```
and
`            ${{ secrets.DOCKER_USERNAME }}/foodgram:${{ steps.date.outputs.tag }}`
That gives us:
![image](https://user-images.githubusercontent.com/67960818/113491164-6b0fa900-94d7-11eb-825c-fa9f691ecb88.png)

**Comment by jb3** [comment]
That's a nice approach, I hadn't thought of versioning like that.

Blackbox right now uses semantic versioning which requires a different approach. I wrote a workflow for my project Olli (https://python-discord.github.io/olli/) yesterday which publishes a `:<sha>` and `:main` tag for any main push and then a `:latest` and `:0.0.1` or whatever tag for an actual GitHub release (pulling the version from the tag name inputted on GitHub).

Release workflow: https://github.com/python-discord/olli/blob/main/.github/workflows/release.yml
Push workflow: https://github.com/python-discord/olli/blob/main/.github/workflows/lint_and_publish.yml

In action: https://github.com/python-discord/olli/actions/runs/712545628

**Comment by matacoder** [comment]
I see your point but changing of semantic version is quite a rare event here (I can see only two versions), but we push often on dockerhub with every new PR. Idea was to fully automatize this action without any input at all.
Actually I've already implemented this approach on MariaDB PR, so you if mind against it I can cut it out.

**Comment by jb3** [comment]
I'm not a maintainer on the project so it's up to @lemonsaurus on what versioning method is used, but personally I'd stick with semantic (as the milestones on this project are configured for).

The real problem here is that the `:latest` tag points to the latest on master and you can't pin to a semver, which would be ideal since even dates can be mutable, whereas a semver is immutable (and pinning to a commit hash isn't a nice solution).

**Comment by lemonsaurus** [comment]
Yeah @jb3, I think the obvious solution here is to tag `:latest` on push to `master`, but tag `:<semver>` on release. Then DockerHub will have available all the same releases as we push to PyPI, which is what we want.

**Comment by jb3** [comment]
I'd personally opt for `:master` to point to the latest master commit and `:latest` instead to point to the latest semver release, that adds a bit of a safeguard from brand new changes being pushed into production environments without any warning.

**Comment by lemonsaurus** [comment]
seems reasonable. Could do that. Or maybe just skip the `:master` entirely, not sure how useful that is to put on DH at all.

**Comment by matacoder** [comment]
So the issue is not an issue at all? No additional code required?

**Comment by lemonsaurus** [comment]
huh? no there's definitely still an issue here, we're not pushing semver-tagged docker containers at all, currently.

Let's go for this implementation:
- No docker builds on push to `master`
- when a GitHub Release is triggered, build and push to DockerHub with two different tags - `:latest` and `:<semver>` (so something like `:v1.0.2`)

**Comment by matacoder** [comment]
Let's keep `main` as `:main` and `GitHub Release` as `:latest` and `:v1.0.2`

**Comment by lemonsaurus** [comment]
Why bother building on push to main anyway? Is that really useful to anyone? If anything we should name it `:experimental` or something then.
