### ISSUE TITLE
Move to Poetry

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#64]
Right now we're using both Pipenv and `setup.py`, which feels bad. We're managing the dependencies in both `Pipfile` and `setup.py`,  and the `Dockerfile` is relying on `pip install -e .` to install dependencies.

Basically this is a mess. We should be using [PEP 517](https://www.python.org/dev/peps/pep-0517/) compatible dependency tracking instead, since that would greatly simplify this.

Let's migrate from Pipenv to Poetry and get rid of the `setup.py` file entirely.

**Comment by matacoder** [comment]
I've read poetry docs and I feel I can do it.
