### ISSUE TITLE
Add description to Dockerhub lemonsaurus/blackbox

### ISSUE THREAD

**Issue by matacoder** [lemonsaurus/blackbox#66]
It's empty now. May be at least link to README on GitHub
[https://hub.docker.com/r/lemonsaurus/blackbox](https://hub.docker.com/r/lemonsaurus/blackbox)

**Comment by lemonsaurus** [comment]
https://github.com/peter-evans/dockerhub-description looked like a promising way to automate this, but sadly it has no support for 2FA and Personal Access Tokens, it requires your actual DockerHub password to an account with no 2FA. 

That's never going to happen, so I guess I'll just copy paste in the readme for now. 🤷🏼

**Comment by lemonsaurus** [comment]
I've added one to the DockerHub readme now, and added a little disclaimer that it might be out of date. 
![image](https://user-images.githubusercontent.com/2098517/123967344-81ce7a80-d9b6-11eb-95ed-a71ad8ac1795.png)
