### ISSUE TITLE
Lint the docstrings!

### ISSUE THREAD

**Issue by lemonsaurus** [lemonsaurus/blackbox#77]
Let's lint docstrings.

We can use [this plugin](https://pypi.org/project/flake8-docstrings/) to do this.

Here are the rule ignores we need to add to `tox.ini` for this plugin:
```
# Missing Docstrings
D100,D104,D105,D107,
# Docstring Whitespace
D203,D212,D214,D215,
# Docstring Quotes
D301,D302,
# Docstring Content
D400,D401,D402,D404,D405,D406,D407,D408,D409,D410,D411,D412,D413,D414,D416,D417
```

We can include those comments in the `tox.ini` as well, and we still want to ignore whatever we're already ignoring.

Once this is done, you'll need to run `pipenv run lint` and fix all linting errors this creates.

**Comment by matacoder** [comment]
Well I did lint every docsting but I am not able to locate `tox.init`. I've added rules to `tox.ini` though.

**Comment by lemonsaurus** [comment]
`tox.init` is just a typo. `tox.ini` is the right place.
